### ISSUE TITLE
build 报错，我这边的环境是go 1.6的，echo库go get 下来的，会不会是echo库的版本问题？请问这咋处理？

### ISSUE THREAD

**Issue by Mjiulee** [ixre/go2o#15]
# go2o/src/x/echox

src/x/echox/echo.go:33: embedded type cannot be a pointer to interface
src/x/echox/echo.go:66: ctx.Response undefined (type _echo.Context is pointer to interface, not interface)
src/x/echox/echo.go:66: ctx.Request undefined (type *echo.Context is pointer to interface, not interface)
src/x/echox/echo.go:82: cannot use this.parseHandler(h) (type func(_echo.Context) error) as type echo.HandlerFunc in argument to this.Echo.Get
src/x/echox/echo.go:87: cannot use this.parseHandler(h) (type func(_echo.Context) error) as type echo.HandlerFunc in argument to this.Echo.Any
src/x/echox/echo.go:92: cannot use this.parseHandler(h) (type func(_echo.Context) error) as type echo.HandlerFunc in argument to this.Echo.Post
src/x/echox/echo.go:98: ctx.Context.Param undefined (type _echo.Context is pointer to interface, not interface)
src/x/echox/echo.go:109: cannot use this.parseHandler(h) (type func(_echo.Context) error) as type echo.HandlerFunc in argument to this.Echo.Any
src/x/echox/echo.go:113: this.Context.String undefined (type *echo.Context is pointer to interface, not interface)
src/x/echox/render.go:24: cannot use new(GoTemplateForEcho) (type *GoTemplateForEcho) as type echo.Renderer in assignment:
    *GoTemplateForEcho does not implement echo.Renderer (wrong type for Render method)
        have Render(io.Writer, string, interface {}) error
        want Render(io.Writer, string, interface {}, echo.Context) error
src/x/echox/echo.go:113: too many errors

**Comment by jsix** [comment]
是的，因为echo 已经讲主干切换为了V2
现在已修复，请重新clone
