### ISSUE TITLE
go build go2o-server.go 编译出错  go 1.6.2

### ISSUE THREAD

**Issue by goodforever** [ixre/go2o#19]
# go2o/src/core/query

src/core/query/partner_query.go:65: gof.CurrentApp.Log().Error undefined (type log.ILogger has no field or method Error)
# go2o/src/core/repository

src/core/repository/member_rep.go:372: undefined: "github.com/jsix/gof/log".Error

**Comment by jsix** [comment]
请重新安装github.com/jsix/gof
go get -u -v github.com/jsix/gof

**Comment by ixre** [comment]
@goodforever 

 已经更换为 go mod 来管理依赖,   克隆代码后直接运行:   `go mod tidy`
