### ISSUE TITLE
安装go-server.go报错

### ISSUE THREAD

**Issue by shuyabin** [ixre/go2o#22]
$ go build go2o-server.go
# command-line-arguments

.\go2o-server.go:85: undefined: app in app.Run

**Comment by jsix** [comment]
是v0.1.1 这个分支吗？
https://github.com/jsix/go2o/tree/v0.1.1

master和develop分支已不包含界面，需要自己实现

**Comment by shuyabin** [comment]
大哥- -能不能让个能跑起来的...都不好和boss推荐

**Comment by jsix** [comment]
https://github.com/jsix/go2o/tree/v0.1.1
应该是没有问题的，群里有人编译OK的

**Comment by coderlee** [comment]
奇怪，难道我下的是假代码？0.1.1编译也不通过，错误类似：
src/core/infrastructure/format/float.go:47: undefined: math.FixFloat32
src/core/query/partner_query.go:21: undefined: gof.Storage
而且，我没找到go2o-server.go，只有go2o-serve.go

**Comment by xuepd** [comment]
v0.1.1的代码怎么获取到，一直没找到ui前端

**Comment by ixre** [comment]
@shuyabin @coderlee @xuepd   fixed , #53
