### ISSUE TITLE
演示测试

### ISSUE THREAD

**Issue by ziranyidu** [ixre/go2o#53]
请问有演示测试的环境吗，我这免费提供也可以。还有UI请问怎么收费，我想体验一下定制

**Comment by jsix** [comment]
还没有演示地址,界面代码在持续重构。有时间会上传个镜像

**Comment by ixre** [comment]
@ziranyidu 已经制作了docker镜像, 参见:[ go2o docker-compose](https://github.com/ixre/go2o/blob/master/docker/docker-compose.yaml)
