### ISSUE TITLE
大佬，请教了

### ISSUE THREAD

**Issue by dotcool** [ixre/go2o#65]
如果用go mod 在go path以外使用master
就会提示这个错误

go: github.com/jsix/gof@v1.3.0: parsing go.mod: unexpected module path "github.com/ixre/gof"
go: github.com/jsix/goex@v1.1.0: parsing go.mod: unexpected module path "github.com/ixre/goex"

**Comment by ouyemasn** [comment]
似乎是地址改了  全局替换github.com/jsix     为 github.com/ixre

**Comment by ixre** [comment]
是的

oyknj <notifications@github.com> 于 2019年5月14日周二 15:02写道：
