### ISSUE TITLE
go2o-web docker-compose is broken

### ISSUE THREAD

**Issue by kaddylover** [ixre/go2o#86]
$ sudo docker pull docker-base.to2.net:5020
Error response from daemon: pull access denied for docker-base.to2.net, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
 $ sudo docker pull docker-base.to2.net:5020/v2
Using default tag: latest
Error response from daemon: Get https://docker-base.to2.net:5020/v2/: http: server gave HTTP response to HTTPS client
$ sudo docker pull docker-base.to2.net:5020/go2o-web
Using default tag: latest
Error response from daemon: Get https://docker-base.to2.net:5020/v2/: http: server gave HTTP response to HTTPS client

Also when I go to https://docker-base.to2.net:5020/v2/ it asks for username/password

**Comment by ixre** [comment]
This registry must use by password. also, you can deploy as docker image standalone!
